### ISSUE TITLE
Service won't connect to Mumble

### ISSUE THREAD

**Issue by mwllgr** [Stieneee/mumble-discord-bridge#64]
Hi,

the bridge is not connecting to my Mumble server and I haven't figured out why, yet.
I am using the following docker-compose:

```yaml
services:

  # Mumble server

  murmur:
    container_name: murmur
    image: mumblevoip/mumble-server:latest
    restart: unless-stopped
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    environment:
       MUMBLE_CONFIG_SERVER_PASSWORD: "pass123"
       MUMBLE_CONFIG_WELCOME_TEXT: "Mumble Server"
       MUMBLE_CONFIG_USERS: "10"
       MUMBLE_CONFIG_BANDWIDTH: "128000"
       MUMBLE_CONFIG_OPUSTHRESHOLD: "0"
    volumes:
      - murmur:/data

  # Mumble-to-Discord bridge

  discord_bridge:
    container_name: murmur_discord
    image: stieneee/mumble-discord-bridge:next
    restart: unless-stopped
    environment:
      DEBUG: "9999"
      MUMBLE_ADDRESS: murmur
      MUMBLE_PASSWORD: pass123
      MUMBLE_INSECURE: "true"
      MUMBLE_USERNAME: Discord
      MUMBLE_CHANNEL: Root
      MODE: "auto"
      DISCORD_TOKEN: "xxxx"
      DISCORD_GID: "108205103000xxxxxxx"
      DISCORD_CID: "108205103000xxxxxxx"
      DISCORD_COMMAND: "phone"
      DISCORD_DISABLE_BOT_STATUS: "true"
    depends_on:
      - murmur
```

Are there any known issues as of right now? Tried the `latest` and the `next` tag of the image.
The bot joins the Discord voice channel but never even logs any attempt of connecting to Mumble.
